#!/usr/bin/env bash
# Generate production settings.toml for Clarinet
# Runs on the target machine. Uses environment variables from setup-services.sh.
#
# Overlay mode (CLARINET_SETTINGS_OVERLAY=1): a downstream project's own
# settings.toml is already installed as the base config — write the
# stand-specific values (secrets, DB/RabbitMQ credentials, root_url, paths)
# to settings.custom.toml instead, which clarinet loads with higher priority.
set -euo pipefail

SETTINGS_DIR="/opt/clarinet"
SETTINGS_FILE="${SETTINGS_DIR}/settings.toml"
OVERLAY="${CLARINET_SETTINGS_OVERLAY:-}"
if [[ -n "$OVERLAY" ]]; then
    SETTINGS_FILE="${SETTINGS_DIR}/settings.custom.toml"
fi
DATA_DIR="/var/lib/clarinet/data"
LOG_DIR="/var/log/clarinet"

# Bare mode on a reused machine: drop a stale stand overlay left by a previous
# project deploy — clarinet loads it with higher priority than the freshly
# generated settings.toml. Only the auto-generated overlay is removed (matched
# by its header signature); operator-managed custom files are left untouched.
CUSTOM_FILE="${SETTINGS_DIR}/settings.custom.toml"
if [[ -z "$OVERLAY" && -f "$CUSTOM_FILE" ]] && head -1 "$CUSTOM_FILE" | grep -q "Clarinet stand overrides"; then
    rm -f "$CUSTOM_FILE"
fi

DB_USER="${CLARINET_DB_USER:-clarinet}"
DB_NAME="${CLARINET_DB_NAME:-clarinet}"
DB_PASS="${CLARINET_DB_PASS:-changeme}"

RABBIT_USER="${CLARINET_RABBIT_USER:-clarinet}"
RABBIT_PASS="${CLARINET_RABBIT_PASS:-changeme}"

SECRET_KEY="${CLARINET_SECRET_KEY:-$(openssl rand -hex 32)}"
ANON_SALT="${CLARINET_ANON_SALT:-$(openssl rand -hex 16)}"

# Preserve existing admin_password on reruns (idempotent)
EXISTING_ADMIN_PASSWORD=""
if [[ -f "$SETTINGS_FILE" ]] && [[ -z "${CLARINET_ADMIN_PASSWORD:-}" ]]; then
    EXISTING_ADMIN_PASSWORD=$(python3 -c "
import tomllib, sys
with open(sys.argv[1], 'rb') as f:
    print(tomllib.load(f).get('admin_password', ''))
" "$SETTINGS_FILE" 2>/dev/null) || EXISTING_ADMIN_PASSWORD=""
fi
ADMIN_PASSWORD="${CLARINET_ADMIN_PASSWORD:-${EXISTING_ADMIN_PASSWORD:-$(openssl rand -hex 8)}}"

ROOT_URL="${CLARINET_ROOT_URL:-}"

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$SCRIPT_DIR/../lib/logging.sh"
init_logging "settings"

# Create directories
mkdir -p "$DATA_DIR" "$LOG_DIR" "$SETTINGS_DIR"
chown -R clarinet:clarinet "$DATA_DIR" "$LOG_DIR"

log "Generating $SETTINGS_FILE..."

# Project identity (name, roles, anon/filter rules, config_* paths) comes from
# the project's own settings.toml in overlay mode — don't override it here.
PROJECT_BLOCK="
# Project
project_name = \"Clarinet\"
"
HEADER="Clarinet production settings"
if [[ -n "$OVERLAY" ]]; then
    PROJECT_BLOCK=""
    HEADER="Clarinet stand overrides (layered over the project's settings.toml)"
fi

cat > "$SETTINGS_FILE" <<TOML
# ${HEADER}
# Auto-generated by generate-settings.sh — $(date -Iseconds)

# Server
host = "127.0.0.1"
port = 8000
debug = false
root_url = "${ROOT_URL}"
api_base_url = "https://127.0.0.1${ROOT_URL}/api"
# Internal loopback to nginx with self-signed certificate — safe to skip verification.
# For production with a real CA certificate, remove this line or set to true.
api_verify_ssl = false
${PROJECT_BLOCK}
# Database
database_driver = "postgresql+asyncpg"
database_host = "localhost"
database_port = 5432
database_name = "${DB_NAME}"
database_username = "${DB_USER}"
database_password = "${DB_PASS}"

# Security
secret_key = "${SECRET_KEY}"
admin_password = "${ADMIN_PASSWORD}"
anon_uid_salt = "${ANON_SALT}"

# Pipeline (TaskIQ + RabbitMQ)
pipeline_enabled = true
rabbitmq_host = "localhost"
rabbitmq_port = 5672
rabbitmq_login = "${RABBIT_USER}"
rabbitmq_password = "${RABBIT_PASS}"

# PACS
pacs_host = "${CLARINET_PACS_HOST:-localhost}"
pacs_port = ${CLARINET_PACS_PORT:-4242}

# Storage
storage_path = "${DATA_DIR}"
log_dir = "${LOG_DIR}"

# Frontend
frontend_enabled = true
ohif_enabled = ${CLARINET_OHIF_ENABLED:-true}
TOML

chmod 640 "$SETTINGS_FILE"
chown clarinet:clarinet "$SETTINGS_FILE"

log "Settings written to $SETTINGS_FILE"
log "Admin password: ${ADMIN_PASSWORD}"
