#!/usr/bin/env bash
# Generate production settings.toml for Clarinet
# Runs on the target machine. Uses environment variables from setup-services.sh.
set -euo pipefail

SETTINGS_DIR="/opt/clarinet"
SETTINGS_FILE="${SETTINGS_DIR}/settings.toml"
DATA_DIR="/var/lib/clarinet/data"
LOG_DIR="/var/log/clarinet"

DB_USER="${CLARINET_DB_USER:-clarinet}"
DB_NAME="${CLARINET_DB_NAME:-clarinet}"
DB_PASS="${CLARINET_DB_PASS:-changeme}"

RABBIT_USER="${CLARINET_RABBIT_USER:-clarinet}"
RABBIT_PASS="${CLARINET_RABBIT_PASS:-changeme}"

SECRET_KEY="${CLARINET_SECRET_KEY:-$(openssl rand -hex 32)}"
ADMIN_PASSWORD="${CLARINET_ADMIN_PASSWORD:-$(openssl rand -base64 12)}"
ANON_SALT="${CLARINET_ANON_SALT:-$(openssl rand -hex 16)}"

ROOT_URL="${CLARINET_ROOT_URL:-}"

GREEN='\033[0;32m'
NC='\033[0m'
log() { echo -e "${GREEN}[settings]${NC} $*"; }

# Create directories
mkdir -p "$DATA_DIR" "$LOG_DIR" "$SETTINGS_DIR"
chown -R clarinet:clarinet "$DATA_DIR" "$LOG_DIR"

log "Generating $SETTINGS_FILE..."

cat > "$SETTINGS_FILE" <<TOML
# Clarinet production settings
# Auto-generated by generate-settings.sh — $(date -Iseconds)

# Server
host = "127.0.0.1"
port = 8000
debug = false
root_url = "${ROOT_URL}"
api_base_url = "https://127.0.0.1${ROOT_URL}/api"
# Internal loopback to nginx with self-signed certificate — safe to skip verification.
# For production with a real CA certificate, remove this line or set to true.
api_verify_ssl = false

# Project
project_name = "Clarinet"

# Database
database_driver = "postgresql+asyncpg"
database_host = "localhost"
database_port = 5432
database_name = "${DB_NAME}"
database_username = "${DB_USER}"
database_password = "${DB_PASS}"

# Security
secret_key = "${SECRET_KEY}"
admin_password = "${ADMIN_PASSWORD}"
anon_uid_salt = "${ANON_SALT}"

# Pipeline (TaskIQ + RabbitMQ)
pipeline_enabled = true
rabbitmq_host = "localhost"
rabbitmq_port = 5672
rabbitmq_login = "${RABBIT_USER}"
rabbitmq_password = "${RABBIT_PASS}"

# PACS
pacs_host = "${CLARINET_PACS_HOST:-localhost}"
pacs_port = ${CLARINET_PACS_PORT:-4242}

# Storage
storage_path = "${DATA_DIR}"
log_dir = "${LOG_DIR}"

# Frontend
frontend_enabled = true
ohif_enabled = ${CLARINET_OHIF_ENABLED:-true}
TOML

chmod 640 "$SETTINGS_FILE"
chown clarinet:clarinet "$SETTINGS_FILE"

log "Settings written to $SETTINGS_FILE"
log "Admin password: ${ADMIN_PASSWORD}"
