clarinet_port = 8001
database_name = "example1"
klara_storage_path = "//10.100.0.104/vol_storage/example1"
klara_url = "http://laris.niioncologii.local:80/example1"
instance_root_url = "/example1"
rabbitmq_max_consumers = 1
klara_path = 'e://RKT_trial/klara'
rabbitmq_exchange = "example1"
rabbitmq_url = "10.100.0.104:5645"
have_gpu = true