"""
Exceptions package for Clarinet framework.

This package provides domain and HTTP exceptions for proper error handling
across different layers of the application.
"""

# Import domain exceptions for services and repositories
from src.exceptions.domain import (
    AlreadyAnonymizedError,
    AnonymizationFailedError,
    AuthenticationError,
    AuthorizationError,
    BusinessRuleViolationError,
    ClarinetError,
    ConfigurationError,
    DatabaseConnectionError,
    DatabaseError,
    DatabaseIntegrityError,
    DicomError,
    DicomFilterError,
    EntityAlreadyExistsError,
    EntityNotFoundError,
    FileAlreadyExistsError,
    FileNotFoundError,
    FilePatternError,
    FileSchemaError,
    FlowConditionError,
    FlowContextError,
    FlowDefinitionError,
    FlowExecutionError,
    ImageError,
    ImageReadError,
    ImageWriteError,
    InsufficientPermissionsError,
    InvalidCredentialsError,
    MigrationError,
    NoScriptError,
    PacsError,
    PatientAlreadyExistsError,
    PatientNotFoundError,
    RecordAlreadyExistsError,
    RecordConstraintViolationError,
    RecordFlowError,
    RecordNotFoundError,
    RecordTypeAlreadyExistsError,
    RecordTypeNotFoundError,
    RequiredFileMissingError,
    RoleAlreadyExistsError,
    RoleNotFoundError,
    ScriptArgumentError,
    ScriptError,
    SeriesAlreadyExistsError,
    SeriesNotFoundError,
    SlicerConnectionError,
    SlicerError,
    SlicerSegmentationError,
    StorageError,
    StudyAlreadyExistsError,
    StudyNotFoundError,
    UserAlreadyExistsError,
    UserAlreadyHasRoleError,
    UserNotFoundError,
    ValidationError,
)

# Import HTTP exceptions for API routers (for backward compatibility)
from src.exceptions.http import (
    BAD_REQUEST,
    CONFLICT,
    FORBIDDEN,
    INTERNAL_SERVER_ERROR,
    NOT_FOUND,
    SERVICE_UNAVAILABLE,
    UNAUTHORIZED,
    UNPROCESSABLE_ENTITY,
    CustomHTTPException,
)

__all__ = [
    "BAD_REQUEST",
    "CONFLICT",
    "FORBIDDEN",
    "INTERNAL_SERVER_ERROR",
    "NOT_FOUND",
    "SERVICE_UNAVAILABLE",
    "UNAUTHORIZED",
    "UNPROCESSABLE_ENTITY",
    "AlreadyAnonymizedError",
    "AnonymizationFailedError",
    "AuthenticationError",
    "AuthorizationError",
    "BusinessRuleViolationError",
    # Domain exceptions
    "ClarinetError",
    "ConfigurationError",
    # HTTP exceptions (for backward compatibility)
    "CustomHTTPException",
    "DatabaseConnectionError",
    "DatabaseError",
    "DatabaseIntegrityError",
    "DicomError",
    "DicomFilterError",
    "EntityAlreadyExistsError",
    "EntityNotFoundError",
    "FileAlreadyExistsError",
    "FileNotFoundError",
    "FilePatternError",
    "FileSchemaError",
    "FlowConditionError",
    "FlowContextError",
    "FlowDefinitionError",
    "FlowExecutionError",
    "ImageError",
    "ImageReadError",
    "ImageWriteError",
    "InsufficientPermissionsError",
    "InvalidCredentialsError",
    "MigrationError",
    "NoScriptError",
    "PacsError",
    "PatientAlreadyExistsError",
    "PatientNotFoundError",
    "RecordAlreadyExistsError",
    "RecordConstraintViolationError",
    "RecordFlowError",
    "RecordNotFoundError",
    "RecordTypeAlreadyExistsError",
    "RecordTypeNotFoundError",
    "RequiredFileMissingError",
    "RoleAlreadyExistsError",
    "RoleNotFoundError",
    "ScriptArgumentError",
    "ScriptError",
    "SeriesAlreadyExistsError",
    "SeriesNotFoundError",
    "SlicerConnectionError",
    "SlicerError",
    "SlicerSegmentationError",
    "StorageError",
    "StudyAlreadyExistsError",
    "StudyNotFoundError",
    "UserAlreadyExistsError",
    "UserAlreadyHasRoleError",
    "UserNotFoundError",
    "ValidationError",
]
