name = "compare_with_projection"
description = "Automatic comparison of doctor segmentation with master model projection"
label = "Compare with projection"
level = "SERIES"
min_records = 1
max_records = 1
role = "auto"

[[files]]
name = "master_projection"
role = "input"
required = true

[[files]]
name = "segmentation_single"
role = "input"
required = true
