name = "create_master_projection"
description = "Manual projection of the master model onto a specific series coordinate space"
label = "Create projection"
level = "SERIES"
min_records = 1
max_records = 1
role = "expert"
slicer_script = "create_projection.py"

[[files]]
name = "master_model"
role = "input"
required = true

[[files]]
name = "master_projection"
role = "output"
required = true
